# DFM_JSON_NAME = {
#     _("Layer Count" ):    "Layer Count",
#     _("Dimensions" ):    "Dimensions",
#     _("Signal Integrity" ):    "Signal Integrity",
#     _("Smallest Trace Width" ):    "Smallest Trace Width",
#     _("Smallest Trace Spacing" ):    "Smallest Trace Spacing",
#     _("Pad size" ):    "Pad size",
#     _("Pad Spacing" ):    "Pad Spacing",
#     _("Hole Size" ):    "Hole Size",
#     _("RingHole" ):    "RingHole",
#     _("Drill Hole Spacing" ):    "Drill Hole Spacing",
#     _("Drill to Copper" ):    "Drill to Copper",
#     _("Board Edge Clearance" ):    "Board Edge Clearance",
#     _("Special Drill Holes" ):    "Special Drill Holes",
#     _("Holes on SMD Pads" ):    "Holes on SMD Pads",
#     _("Missing SMask Openings" ):    "Missing SMask Openings",
#     _("Drill Hole Density" ):    "Drill Hole Density",
#     _("Surface Finish Area" ):    "Surface Finish Area",
#     _("Test Point Count" ):    "Test Point Count",
# }


Language_chinese = {
    "Signal Integrity": "电气信号",
    "Smallest Trace Width": "最小线宽",
    "Smallest Trace Spacing": "最小间距",
    "SMD Spacing": "SMD间距",
    "Pad size": "最小焊盘",
    "Pad Spacing": "焊盘间距",
    "Hole Size": "钻孔孔径",
    "Hole Diameter": "钻孔孔径",
    "RingHole": "孔环",
    "Drill Hole Spacing": "孔到孔",
    "Drill to Copper": "孔到铜",
    "Board Edge Clearance": "板边距离",
    "Special Drill Holes": "特殊孔",
    "Holes on SMD Pads": "孔上焊盘",
    "Missing SMask Openings": "阻焊开窗",
    "Solder Mask Analysis": "阻焊分析",
    "Drill Hole Density": "孔密度",
    "Surface Finish Area": "沉金面积",
    "Test Point Count": "飞针点数",
    "pcs": "个",
    "show": "显示所有",
    "via_ring": "via孔环",
    "pth_ring": "pth孔环",
    "long_pads": "长条焊盘",
    "short_pads": "常规焊盘",
    "line_width": "最小线宽",
    "unconnected traces": "断头线",
    "floating copper": "孤立铜",
    "unconnected vias": "无效过孔",
    "acute angle traces": "锐角",
    "dangling tracks": "悬空端点",
    "trace spacing": "线到线",
    "trace-to-pad spacing": "焊盘到线",
    "pad-to-pad spacing": "焊盘到焊盘",
    "pad spacing": "焊盘间距",
    "bga pads": "bga焊盘",
    "short pads": "常规焊盘",
    "long pads": "长条焊盘",
    "smd pad spacing": "smd焊盘间距",
    "grid width": "网格线宽",
    "grid spacing": "网格间距",
    "smallest drill size": "最小Via(过孔)",
    "aspect ratio": "孔厚径比",
    "smallest slot width": "最小槽宽",
    "largest drill size": "最大孔径",
    "largest pth size": "最大插件孔径",
    "largest slot width": "最大槽宽",
    "largest slot length": "最大槽长",
    "slot aspect ratio": "槽长宽比",
    "square hole size": "方孔尺寸",
    "largest blind/buried via": "最大盲埋孔",
    "via annular ring": "via孔环",
    "pth annular ring": "pth孔环",
    "pth-to-trace [outer]": "PTH孔到外层走线",
    "pth-to-trace [inner]": "PTH孔到内层走线",
    "via-to-trace [outer]": "过孔到外层走线",
    "via-to-trace [inner]": "过孔到内层走线",
    "npth-to-copper": "NPTH孔到铜",
    "smd-to-board edge": "smd到板边",
    "copper-to-board edge": "铜到板边",
    "hole-to-board edge": "孔到板边",
    "pth-to-board edge": "插件孔到板边",
    "via-to-board edge": "Via到板边",
    "screw hole-to-board edge": "螺丝孔到板边",
    "npth-to-board edge": "NPTH孔到板边",
    "square/rectangular drills": "正/长方形孔",
    "castellated holes": "半孔",
    "pth on smd pad": "SMD焊盘上PTH孔",
    "via on smd pad": "SMD焊盘上过孔",
    "npth on smd pad": "SMD焊盘上NPTH孔",
    "missing smask opening": "阻焊少开窗",
    "solder mask bridge": "阻焊桥",
    "solder mask covers trace": "阻焊盖线",
    "solder mask covers multiple nets": "阻焊覆盖多个网络",
    "same net via spacing": "同网络过孔",
    "different net via spacing": "不同网络过孔",
    "different net pth spacing": "不同网络插件孔",
    "blind/buried via spacing": "盲埋孔距离",
    "trace mssing": "网络断连",
    "trace missing": "网络断连",
    "smallest pth": "最小插件孔",
    "smallest pth size": "最小插件孔",
    "smallest via [mec]": "最小机械过孔",
    "smallest blind_laser": "最小激光盲孔",
    "smallest blind_mec": "最小机械盲孔",
    "smallest buried_laser": "最小激光埋孔",
    "smallest buried_mec": "最小机械埋孔",
    "trace-to-board edge": "线到板边",
    "via on bga pad": "BGA焊盘上过孔",
    "basic": "普通工艺",
    "standard": "标准工艺",
    "advanced": "高阶工艺",
}

Language_english = {
    "signal integrity": "Signal Integrity",
    "smallest trace spacing": "Smallest Trace Spacing",
    "smd spacing": "SMD Spacing",
    "pad size": "Pad Size",
    "hole size": "Hole Size",
    "hole diameter": "Hole Size",
    "ringhole": "Annular Ring",
    "drill hole spacing": "Drill Hole Spacing",
    "drill to copper": "Drill to Copper",
    "special drill holes": "Special Drill Holes",
    "holes on smd pads": "Holes on SMD Pads",
    "missing smask openings": "Missing SMask Openings",
    "solder mask analysis": "Solder Mask Analysis",
    "via_ring": "Via Annular Ring",
    "pth_ring": "PTH Annular Ring",
    "long_pads": "Long Pads",
    "short_pads": "Short Pads",
    "line_width": "Smallest Trace Width",
    "layer": "layer",
    "type": "problem",
    "result": "occurrences(click to view)",
    "save_layer": "keep selected layers",
    "pcs": "pcs",
    "show": "show all",
    "unconnected traces": "Unconnected Traces",
    "floating copper": "Floating Copper",
    "unconnected vias": "Unconnected Vias",
    "acute angle traces": "Acute Angle Traces",
    "dangling tracks": "Dangling Tracks",
    "smallest trace width": "Smallest Trace Width",
    "trace spacing": "Trace Spacing",
    "trace-to-pad spacing": "Trace-to-Pad Spacing",
    "pad-to-pad spacing": "Pad-to-Pad Spacing",
    "pad spacing": "Pad-to-Pad Spacing",
    "bga pads": "BGA Pads",
    "short pads": "Short Pads",
    "long pads": "Long Pads",
    "smd pad spacing": "SMD Pad Spacing",
    "smallest drill size": "Smallest Drill Size",
    "aspect ratio": "Aspect Ratio",
    "smallest slot width": "Smallest Slot Width",
    "largest drill size": "Largest Drill Size",
    "largest pth size": "Largest PTH Size",
    "largest slot width": "Largest Slot Width",
    "largest slot length": "Largest Slot Length",
    "slot aspect ratio": "Slot Aspect Ratio",
    "square hole size": "Square Hole Size",
    "largest blind/buried via": "Largest Blind/Buried Via",
    "via annular ring": "Via Annular Ring",
    "pth annular ring": "PTH Annular Ring",
    "pth-to-trace [outer]": "PTH-to-Trace [Outer]",
    "pth-to-trace [inner]": "PTH-to-Trace [Inner]",
    "via-to-trace [outer]": "Via-to-Trace [Outer]",
    "via-to-trace [inner]": "Via-to-Trace [Inner]",
    "npth-to-copper": "NPTH-to-Copper",
    "smd-to-board edge": "SMD-to-Board Edge",
    "copper-to-board edge": "Copper-to-Board Edge",
    "hole-to-board edge": "Hole-to-Board Edge",
    "pth-to-board edge": "PTH-to-Board Edge",
    "via-to-board edge": "Via-to-Board Edge",
    "screw hole-to-board edge": "Screw Hole-to-Board Edge",
    "npth-to-board edge": "NPTH-to-Board Edge",
    "square/rectangular drills": "Square/Rectangular Drills",
    "castellated holes": "Castellated Holes",
    "pth on smd pad": "PTH on SMD Pad",
    "via on smd pad": "Via on SMD Pad",
    "npth on smd pad": "NPTH on SMD Pad",
    "missing smask opening": "Missing SMask Opening",
    "solder mask bridge": "Solder Mask Bridge",
    "solder mask covers trace": "Solder Mask Covers Trace",
    "solder mask covers multiple nets": "Solder Mask Covers Multiple Nets",
    "same net via spacing": "Same Net Via Spacing",
    "different net via spacing": "Different Net Via Spacing",
    "different net pth spacing": "Different Net PTH Spacing",
    "blind/buried via spacing": "Blind/Buried Via Spacing",
    "trace mssing": "Trace Missing",
    "trace missing": "Trace Missing",
    "smallest pth": "Smallest PTH",
    "smallest pth size": "Smallest PTH",
    "smallest via [mec]": "Smallest Via [mec]",
    "smallest blind_laser": "Smallest Blind_Laser",
    "smallest blind_mec": "Smallest Blind_mec",
    "smallest buried_laser": "Smallest Buried_Laser",
    "smallest buried_mec": "Smallest Buried_mec",
    "trace-to-board edge": "Trace-to-Board Edge",
    "via on bga pad": "Via on BGA Pad",
    "basic": "Basic",
    "standard": "Standard",
    "advanced": "Advanced",
}
