# DFM_JSON_NAME = {
#     _("Layer Count" ):    "Layer Count",
#     _("Dimensions" ):    "Dimensions",
#     _("Signal Integrity" ):    "Signal Integrity",
#     _("Smallest Trace Width" ):    "Smallest Trace Width",
#     _("Smallest Trace Spacing" ):    "Smallest Trace Spacing",
#     _("Pad size" ):    "Pad size",
#     _("Pad Spacing" ):    "Pad Spacing",
#     _("Hatched Copper Pour" ):    "Hatched Copper Pour",
#     _("Hole Diameter" ):    "Hole Diameter",
#     _("RingHole" ):    "RingHole",
#     _("Drill Hole Spacing" ):    "Drill Hole Spacing",
#     _("Drill to Copper" ):    "Drill to Copper",
#     _("Board Edge Clearance" ):    "Board Edge Clearance",
#     _("Special Drill Holes" ):    "Special Drill Holes",
#     _("Holes on SMD Pads" ):    "Holes on SMD Pads",
#     _("Missing SMask Openings" ):    "Missing SMask Openings",
#     _("Drill Hole Density" ):    "Drill Hole Density",
#     _("Surface Finish Area" ):    "Surface Finish Area",
#     _("Test Point Count" ):    "Test Point Count",
# }


Language_chinese = {
    "Signal Integrity": "电气信号",
    "Smallest Trace Width": "最小线宽",
    "Smallest Trace Spacing": "最小间距",
    "Pad size": "最小焊盘",
    "Pad Spacing": "焊盘间距",
    "Hatched Copper Pour": "网格铺铜",
    "Hole Diameter": "孔大小",
    "RingHole": "孔环",
    "Drill Hole Spacing": "孔到孔",
    "Drill to Copper": "孔到线",
    "Board Edge Clearance": "板边距离",
    "Special Drill Holes": "特殊孔",
    "Holes on SMD Pads": "孔上焊盘",
    "Missing SMask Openings": "阻焊开窗",
    "Drill Hole Density": "孔密度",
    "Surface Finish Area": "沉金面积",
    "Test Point Count": "飞针点数",
    "pcs": "个",
    "picture_path": "_zh.png",
    "show": "显示所有",
    "via_ring": "via孔环",
    "pth_ring": "pth孔环",
    "long_pads": "长条焊盘",
    "short_pads": "常规焊盘",
    "line_width": "最小线宽",
    "grid_width": "网格线宽",
    "grid_spacing": "网格线距",
    "unconnected traces": "断头线",
    "floating copper": "孤立铜",
    "unconnected vias": "无效过孔",
    "acute angle traces": "锐角",
    "trace spacing": "线到线",
    "trace-to-pad spacing": "焊盘到线",
    "pad spacing": "焊盘间距",
    "bga pads": "bga焊盘",
    "short pads": "常规焊盘",
    "long pads": "长条焊盘",
    "smd pad spacing": "smd焊盘间距",
    "grid width": "网格线宽",
    "grid spacing": "网格间距",
    "smallest drill size": "最小孔径",
    "aspect ratio": "孔后径比",
    "smallest slot width": "最小槽宽",
    "largest drill size": "最大孔径",
    "largest slot width": "最大槽宽",
    "largest slot length": "最大槽长",
    "slot aspect ratio": "槽长宽比",
    "largest blind/buried via": "最大盲埋孔",
    "via annular ring": "via孔环",
    "pth annular ring": "pth孔环",
    "pth-to-trace [outer]": "插件孔到表层",
    "pth-to-trace [inner]": "插件孔到内层",
    "via-to-trace [outer]": "过孔到表层",
    "via-to-trace [inner]": "过孔到内层",
    "npth-to-copper": "npth铜",
    "smd-to-board edge": "smd到板边",
    "copper-to-board edge": "铜到板边",
    "square/rectangular drills": "正长方形孔",
    "castellated holes": "半孔",
    "via-in-pad": "盘中孔",
    "pth on smd pad": "插件孔上焊盘",
    "via on smd pad": "过孔上焊盘",
    "npth on smd pad": "npth孔上焊盘",
    "missing smask opening": "阻焊少开窗",
    "same net via spacing": "通网络过孔",
    "different net via spacing": "不同网络过孔",
    "different net pth spacing": "不同网络插件孔",
    "blind/buried via spacing": "盲埋孔距离",
}

Language_english = {
    "via_ring": "Via Annular Ring",
    "pth_ring": "PTH Annular Ring",
    "long_pads": "Long Pads",
    "short_pads": "Short Pads",
    "line_width": "Smallest Trace Width",
    "grid_width": "Grid Width",
    "grid_spacing": "Grid Spacing",
    "layer": "layer",
    "type": "problem",
    "result": "occurrences(click to view)",
    "save_layer": "keep selected layers",
    "pcs": "pcs",
    "picture_path": "_en.png",
    "show": "show all",
    "via_ring": "via孔环",
    "pth_ring": "pth孔环",
    "long_pads": "长条焊盘",
    "short_pads": "常规焊盘",
    "line_width": "最小线宽",
    "grid_width": "网格线宽",
    "grid_spacing": "网格线距",
    "unconnected traces": "断头线",
    "floating copper": "孤立铜",
    "unconnected vias": "无效过孔",
    "acute angle traces": "锐角",
    "smallest trace width": "最小线宽",
    "trace spacing": "线到线",
    "trace-to-pad spacing": "焊盘到线",
    "pad spacing": "焊盘间距",
    "bga pads": "bga焊盘",
    "short pads": "常规焊盘",
    "long pads": "长条焊盘",
    "smd pad spacing": "smd焊盘间距",
    "grid width": "网格线宽",
    "grid spacing": "网格间距",
    "smallest drill size": "最小孔径",
    "aspect ratio": "孔后径比",
    "smallest slot width": "最小槽宽",
    "largest drill size": "最大孔径",
    "largest slot width": "最大槽宽",
    "largest slot length": "最大槽长",
    "slot aspect ratio": "槽长宽比",
    "largest blind/buried via": "最大盲埋孔",
    "via annular ring": "via孔环",
    "pth annular ring": "pth孔环",
    "pth-to-trace [outer]": "插件孔到表层",
    "pth-to-trace [inner]": "插件孔到内层",
    "via-to-trace [outer]": "过孔到表层",
    "via-to-trace [inner]": "过孔到内层",
    "npth-to-copper": "npth铜",
    "smd-to-board edge": "smd到板边",
    "copper-to-board edge": "铜到板边",
    "square/rectangular drills": "正长方形孔",
    "castellated holes": "半孔",
    "via-in-pad": "盘中孔",
    "pth on smd pad": "插件孔上焊盘",
    "via on smd pad": "过孔上焊盘",
    "npth on smd pad": "npth孔上焊盘",
    "missing smask opening": "阻焊少开窗",
    "same net via spacing": "通网络过孔",
    "different net via spacing": "不同网络过孔",
    "different net pth spacing": "不同网络插件孔",
    "blind/buried via spacing": "盲埋孔距离",
}
