RULE_SOURCE_OFFICIAL_SAMPLE = "official_service_sample"
RULE_SOURCE_HQPCB_CAPABILITY = "hqpcb_public_capability"
RULE_SOURCE_PLUGIN_DEFAULT = "plugin_default"


RULE_CATALOG = {
    "Signal Integrity": (
        {
            "item": "Trace Mssing",
            "rule": "39.370079,39.370079,78.740157",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Disconnected copper trace fragments returned by the DFM service.",
        },
        {
            "item": "Acute Angle Traces",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Acute trace/copper angles that may trap acid or create weak copper.",
        },
        {
            "item": "Dangling Tracks",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Track ends that are not connected to a pad, via, or other copper.",
        },
        {
            "item": "Floating Copper",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Copper islands that are isolated from useful nets.",
        },
        {
            "item": "Unconnected Vias",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Vias without effective copper connectivity.",
        },
    ),
    "Smallest Trace Width": (
        {
            "item": "Smallest Trace Width",
            "rule": "0.127000,0.150000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Minimum copper trace width. Public HQPCB capability lists 5 mil as the lower bound for common orders.",
        },
    ),
    "Smallest Trace Spacing": (
        {
            "item": "Trace Spacing",
            "rule": "0.127000,0.150000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Minimum clearance between copper traces.",
        },
        {
            "item": "Trace-to-Pad Spacing",
            "rule": "0.127000,0.150000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Minimum clearance between traces and pads.",
        },
        {
            "item": "Pad-to-Pad Spacing",
            "rule": "0.127000,0.150000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Minimum general clearance between copper pads.",
        },
        {
            "item": "BGA Pads",
            "rule": "0.100000,0.127000,999.000000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Minimum edge-to-edge clearance between BGA pads.",
        },
    ),
    "SMD Spacing": (
        {
            "item": "SMD Pad Spacing",
            "rule": "0.152400,0.203200,0.254000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Minimum edge-to-edge clearance between SMD pads.",
        },
    ),
    "Pad size": (
        {
            "item": "Short Pads",
            "rule": "0.203200,0.304800,0.508000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum shorter-side length of ordinary pads.",
        },
        {
            "item": "Long Pads",
            "rule": "0.152400,0.177800,0.254000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Undersized elongated pads have low adhesion, which can reduce manufacturing quality and yield and may increase testing costs. Use a minimum width of at least 0.15 mm; 0.2 mm or greater is recommended.",
            "description_only": True,
        },
    ),
    "Hole Size": (
        {
            "item": "Smallest Drill Size",
            "rule": "0.190000,0.250000,0.300000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Too-small through-vias can reduce production efficiency and yield and may increase cost. Use a via drill diameter of at least 0.3 mm.",
            "description_only": True,
        },
        {
            "item": "Smallest PTH",
            "rule": "0.290000,0.450000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum component PTH pad drill diameter; excludes vias and NPTH pads.",
        },
        {
            "item": "Largest Drill Size",
            "rule": "999.000000,6.300000,6.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Maximum generic drill size used by the remote DFM contract.",
        },
        {
            "item": "Largest PTH Size",
            "rule": "999.000000,6.300000,6.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Maximum plated through-hole size.",
        },
        {
            "item": "Aspect Ratio",
            "rule": "12.000000,10.000000,8.000000",
            "unit": "ratio",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "As drill diameter decreases, usable flute length also decreases; very small drills may not penetrate a thick PCB.",
            "description_only": True,
        },
        {
            "item": "Smallest Via [mec]",
            "rule": "0.190000,0.250000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum mechanical via drill.",
        },
        {
            "item": "Smallest Blind_Laser",
            "rule": "0.090000,0.130000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum laser blind via drill.",
        },
        {
            "item": "Smallest Blind_mec",
            "rule": "0.190000,0.250000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum mechanically drilled blind via.",
        },
        {
            "item": "Smallest Buried_Laser",
            "rule": "0.090000,0.130000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum laser buried via drill.",
        },
        {
            "item": "Smallest Buried_mec",
            "rule": "0.190000,0.250000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum mechanically drilled buried via.",
        },
        {
            "item": "Smallest Slot Width",
            "rule": "0.450088,0.599948,5.999988",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "The minimum oval-slot cutter diameter is 0.4 mm. The original slot must not be narrower than 0.3 mm; use at least 0.4 mm, with 0.6 mm or greater recommended.",
            "description_only": True,
        },
        {
            "item": "Largest Blind/Buried Via",
            "rule": "0.500000,0.400000,0.300000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Maximum blind or buried via drill.",
        },
        {
            "item": "Largest Slot Length",
            "rule": "15.000000,12.000000,10.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Oversized slots require additional production operations, reducing efficiency and increasing cost. Keep the slot length at or below 10 mm.",
            "description_only": True,
        },
        {
            "item": "Largest Slot Width",
            "rule": "8.000000,7.000000,6.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Oversized slot widths require additional production operations, reducing efficiency and increasing cost. Keep the cutter diameter at or below 5.8 mm.",
            "description_only": True,
        },
        {
            "item": "Slot Aspect Ratio",
            "rule": "1.500000,2.000000,999.000000",
            "unit": "ratio",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "When slot length is less than twice its width, uneven forces during production can deform it. Use a slot length of at least twice the width.",
            "description_only": True,
        },
    ),
    "RingHole": (
        {
            "item": "Via Annular Ring",
            "rule": "0.101600,0.127000,0.152400",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Minimum annular ring for vias.",
        },
        {
            "item": "PTH Annular Ring",
            "rule": "0.152400,0.177800,0.203200",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_HQPCB_CAPABILITY,
            "offline_status": "implemented",
            "description": "Minimum annular ring for plated through-hole pads.",
        },
    ),
    "Drill Hole Spacing": (
        {
            "item": "Same Net Via Spacing",
            "rule": "0.254000,0.300000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Minimum spacing between vias on the same net.",
        },
        {
            "item": "Different Net Via Spacing",
            "rule": "0.254000,0.300000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Minimum spacing between vias on different nets.",
        },
        {
            "item": "Different Net PTH Spacing",
            "rule": "0.400050,0.450088,0.500126",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": (
                "Insufficient hole-to-hole spacing can reduce production "
                "efficiency and quality yield. Use a minimum spacing of at "
                "least 15 mil; 17 mil or greater is recommended."
            ),
            "description_only": True,
        },
        {
            "item": "Blind/Buried Via Spacing",
            "rule": "0.254000,0.300000,999.000000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Minimum spacing between blind/buried vias.",
        },
    ),
    "Drill to Copper": (
        {
            "item": "PTH-to-Trace [Outer]",
            "rule": "0.200000,0.250000,999.000000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Outer-layer clearance from plated through-hole edge to trace.",
        },
        {
            "item": "PTH-to-Trace [Inner]",
            "rule": "0.250000,0.300000,999.000000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Inner-layer clearance from plated through-hole edge to trace.",
        },
        {
            "item": "Via-to-Trace [Outer]",
            "rule": "0.200000,0.250000,999.000000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Outer-layer clearance from via edge to trace.",
        },
        {
            "item": "Via-to-Trace [Inner]",
            "rule": "0.250000,0.300000,999.000000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Inner-layer clearance from via edge to trace.",
        },
        {
            "item": "NPTH-to-Copper",
            "rule": "0.200000,0.250000,999.000000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_PLUGIN_DEFAULT,
            "offline_status": "implemented",
            "description": "Clearance from non-plated hole edge to copper.",
        },
    ),
    "Copper-to-Board Edge": (
        {
            "item": "SMD-to-Board Edge",
            "rule": "0.254000,0.381000,0.508000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum distance from SMD pad to board edge.",
        },
        {
            "item": "Trace-to-Board Edge",
            "rule": "0.203000,0.279000,0.381000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum distance from trace to board edge.",
        },
        {
            "item": "Copper-to-Board Edge",
            "rule": "0.203000,0.279000,0.381000",
            "unit": "mm",
            "kind": "min",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum distance from copper pour or copper feature to board edge.",
        },
    ),
    "Hole-to-Board Edge": (
        {
            "item": "PTH-to-Board Edge",
            "rule": "0.400050,0.500126,0.599948",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "PTH holes too close to the board edge risk breakout and may severely affect electrical performance. Use at least 12 mil; 15 mil or greater is recommended.",
            "description_only": True,
        },
        {
            "item": "Via-to-Board Edge",
            "rule": "0.299974,0.400050,0.500126",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Vias too close to the board edge risk breakout and may severely affect electrical performance. Use at least 12 mil; 15 mil or greater is recommended.",
            "description_only": True,
        },
        {
            "item": "Screw Hole-to-Board Edge",
            "rule": "0.400050,0.500126,0.599948",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Screw holes too close to the board edge risk breakout. Use at least 8 mil; 12 mil or greater is recommended.",
            "description_only": True,
        },
        {
            "item": "NPTH-to-Board Edge",
            "rule": "0.199898,0.299974,0.400050",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "NPTH holes too close to the board edge risk breakout. Use at least 8 mil; 12 mil or greater is recommended.",
            "description_only": True,
        },
    ),
    "Special Drill Holes": (
        {
            "item": "Square/Rectangular Drills",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": (
                "Right-angle corners in square or rectangular holes cannot be "
                "machined in the production process. Use a circular or oval "
                "hole instead."
            ),
            "description_only": True,
        },
        {
            "item": "Castellated Holes",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Castellated or half-hole feature detection.",
        },
    ),
    "Holes on SMD Pads": (
        {
            "item": "Via on BGA Pad",
            "rule": "0.010000,0.010000,0.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Via overlap with BGA pad.",
        },
        {
            "item": "Via on SMD Pad",
            "rule": "0.150000,0.050000,0.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Via overlap with SMD pad.",
        },
        {
            "item": "NPTH on SMD Pad",
            "rule": "0.100000,0.010000,0.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "NPTH overlap with SMD pad.",
        },
        {
            "item": "PTH on SMD Pad",
            "rule": "0.100000,0.050000,0.000000",
            "unit": "mm",
            "kind": "max",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "PTH overlap with SMD pad.",
        },
    ),
    "Missing SMask Openings": (
        {
            "item": "Missing SMask Opening",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Pad or copper feature that should expose solder mask but has no opening.",
        },
    ),
    "Solder Mask Analysis": (
        {
            "item": "Solder Mask Bridge",
            "rule": "0.127000,0.152400,0.254000",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Minimum solder-mask web between separate openings.",
        },
        {
            "item": "Solder Mask Covers Trace",
            "rule": "0.038100,0.050800,0.063500",
            "unit": "mm",
            "kind": "min",
            "profile_scale": "fixed",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "Clearance from a mask opening to a trace on another net.",
        },
        {
            "item": "Solder Mask Covers Multiple Nets",
            "rule": "-,-,-",
            "unit": "",
            "kind": "boolean",
            "source": RULE_SOURCE_OFFICIAL_SAMPLE,
            "offline_status": "implemented",
            "description": "One connected solder-mask opening exposes copper from multiple nets.",
        },
    ),
}


def default_rule_items(category):
    return tuple((rule["item"], rule["rule"]) for rule in RULE_CATALOG.get(category, ()))


def default_rule_metadata(category):
    return RULE_CATALOG.get(category, ())


def default_rule_for(category, item):
    normalized_item = normalize_name(item)
    for rule in RULE_CATALOG.get(category, ()):
        if normalize_name(rule["item"]) == normalized_item:
            return rule["rule"]
    return ""


def normalize_name(value):
    return "".join(ch for ch in str(value or "").lower() if ch.isalnum())
