PICTURE_BY_ITEM = {
    "acute_angle": ("acute angle traces", "锐角"),
    "breakage_line": ("unconnected traces", "trace mssing", "trace missing", "断头线"),
    "dangling_tracks": ("dangling tracks", "悬空端点", "悬空断点"),
    "isolated_copper": ("floating copper", "孤立铜"),
    "invalid_via": ("unconnected vias", "无效过孔"),
    "line_width": ("smallest trace width", "最小线宽"),
    "line2line": ("trace spacing", "线到线"),
    "pad2line": ("trace-to-pad spacing", "焊盘到线"),
    "pad2pad": ("pad spacing", "pad-to-pad spacing", "焊盘间距", "焊盘到焊盘"),
    "bga": ("bga pads", "short pads", "long pads", "bga焊盘", "长条焊盘", "常规焊盘"),
    "pad_spacing_base": ("smd pad spacing", "smd焊盘间距"),
    "min_diameter": ("smallest drill size", "smallest pth", "最小Via(过孔)", "最小插件孔"),
    "min_thick_diameter": ("aspect ratio", "孔厚径比", "孔后径比"),
    "min_slot": ("smallest slot width", "最小槽宽"),
    "max_diameter": ("largest drill size", "largest pth size", "最大孔径"),
    "max_slot": ("largest slot width", "最大槽宽"),
    "max_slot_length": ("largest slot length", "最大槽长"),
    "slot_length_width": ("slot aspect ratio", "槽长宽比"),
    "max_diameter_blind_buried": ("largest blind/buried via", "最大盲埋孔"),
    "via_ring": ("via annular ring", "pth annular ring", "via孔环", "pth孔环"),
    "line2pth_outer": (
        "pth-to-trace [outer]", "via-to-trace [outer]",
        "插件孔到表层", "过孔到表层", "PTH孔到外层走线", "过孔到外层走线",
    ),
    "line2pth_inner": (
        "pth-to-trace [inner]", "via-to-trace [inner]",
        "插件孔到内层", "过孔到内层", "PTH孔到内层走线", "过孔到内层走线",
    ),
    "npth2copper": ("npth-to-copper", "npth铜", "NPTH孔到铜"),
    "smd2edge": ("smd-to-board edge", "smd到板边"),
    "copper2edge": ("copper-to-board edge", "trace-to-board edge", "铜到板边", "线到板边"),
    "pth2edge": ("pth-to-board edge", "插件孔到板边"),
    "via2edge": ("via-to-board edge", "Via到板边"),
    "npth2edge": (
        "screw hole-to-board edge", "npth-to-board edge",
        "螺丝孔到板边", "NPTH孔到板边",
    ),
    "hole_spuared": ("square/rectangular drills", "正/长方形孔"),
    "hole_half": ("castellated holes", "半孔"),
    "pth_insmd": ("pth on smd pad", "SMD焊盘上PTH孔", "插件孔上焊盘"),
    "via_insmd": ("via on smd pad", "via on bga pad", "SMD焊盘上过孔", "过孔上焊盘", "BGA焊盘上过孔"),
    "npth_insmd": ("npth on smd pad", "SMD焊盘上NPTH孔", "NPTH孔上焊盘"),
    "soldmask_lack": ("missing smask opening", "阻焊少开窗"),
    "solder_mask_bridge": ("solder mask bridge", "阻焊桥"),
    "solder_mask_covers_trace": ("solder mask covers trace", "阻焊盖线"),
    "solder_mask_multiple_nets": (
        "solder mask covers multiple nets",
        "阻焊覆盖多个网络",
    ),
    "via_same net": ("same net via spacing", "同网络过孔", "通网络过孔"),
    "via_difference_net": ("different net via spacing", "不同网络过孔"),
    "pth_difference_net": ("different net pth spacing", "不同网络插件孔"),
    "blind2blind": ("blind/buried via spacing", "盲埋孔距离"),
}
